name: Data Processor

on: 
  workflow_dispatch:

jobs:
  python_job:
    runs-on: ubuntu-latest
    steps:
    
    - name: Cache PIP Packages
      uses: actions/cache@v3
      with:
        path: /usr/local/lib/python3.10/
        key: pip-keys
        restore-keys: pip-keys
    
        
    - name: List current dir.
      run: |
         ls -la "/usr/local/lib/"
         python3 --version
    
    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content

    - name: Install python packages....
      run: |
          python -m pip install --upgrade pip
          sudo apt install clang
          pip3 install bs4 requests lxml Scrapy
    
    - name: Run
      run: bash dev/start.sh
