name: Data Telegram Updater

on: 
  workflow_dispatch:

jobs:
  telegram_job:
    runs-on: ubuntu-latest
    steps:
    
    - name: Cache Hashed Jobs
      uses: actions/cache@v3
      with:
        path: ./hashed_jobs/
        key: ${{ runner.os }}-hashed_jobs-${{ hashFiles('hashed.txt') }}
        restore-keys: |
          ${{ runner.os }}-hashed_jobs-${{ hashFiles('hashed.txt') }}
    
    - name: Test Run 1
      run: |  
        echo ls -la
   
    - name: Checkout Repo Content
      uses: actions/checkout@v2
      
    - name: Test Run 2
      run: |  
        echo ls -la
 
    - name: Run
      env:
        OLJ_JOB_URL: ${{secrets.OLJ_JOBURL}}
        OLJ_JOB_URL_PATTERN: ${{secrets.OLJ_JOB_URL_PATTERN}}
        TELEGRAM_API: ${{secrets.TELEGRAM_API}}
        TELEGRAM_MESSAGE: ${{secrets.TELEGRAM_MESSAGE}}
      run: |
         sh dev/oljtelegram.sh
